/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utilidades.Persistencia.DAO;

/**
 *
 * @author Führer
 */
public class ParametroGeneralDAO {

    private static final String INSERTAR_PARAMETRO = "INSERT INTO T_INV_PARAMETROGENERAL (EM_PROPIETARIA,FUNDO,RODAL,ANO_PLANTACION,ES_PRINCIPAL,ES_SECUNDARIA,NM_ESPECIES,CD_ORDEN_TRABAJO,FC_MEDICION,TP_INVENTARIO,NM_PARCELAS,SUPERFICIE_PARCELAS,EM_DE_SERVICIOS,FC_PROYECCION,DENSIDAD,DENSIDAD_P,DENSIDAD_MP,DAP_MEDIO,DAP_MEDIO_P,DAP_MEDIO_MP,AREA_BASAL,AREA_BASAL_P,AREA_BASAL_MP,ALTURA_TOTAL_MEDIA,ALTURA_TOTAL_MEDIA_P,ALTURA_TOTAL_MEDIA_MP,VOLUMEN,VOLUMEN_P,VOLUMEN_MP,MOD_ALTURA,B0,B1,B2,B3,B4,B5,B6,AJUSTE,SUPERFICIE_RODAL) VALUES (";
    private static final String OBTENER_MAX_PARAMETRO = "SELECT MAX(CD_ORDEN_TRABAJO) AS MAX FROM DSI.T_INV_PARAMETROGENERAL";
    private static final String ELIMINA_PARAMETRO = "DELETE FROM T_INV_PARAMETROGENERAL WHERE CD_ORDEN_TRABAJO = '";

}
